[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project]
name = "msauth-browser"
version = "0.1.0"
description = "🎭 Extract Microsoft OAuth tokens using Playwright browser automation."
authors = [
    {name = "n3rada",email = "72791564+n3rada@users.noreply.github.com"}
]
license = {text = "GPL-3.0-or-later"}
readme = "README.md"
requires-python = ">=3.11,<4.0"

dependencies = [
    "loguru (>=0.7.3,<0.8.0)",
    "httpx[socks] (>=0.28.1,<0.29.0)",
    "pkce (>=1.0.3,<2.0.0)",
    "playwright (>=1.52.0,<2.0.0)",
    "pyperclip (>=1.11.0,<2.0.0)",
]

[project.urls]
repository = "https://github.com/n3rada/msauth-browser"

[project.scripts]
msauth-browser = 'msauth_browser.console:run'

